## Lexicon for parser

tokens = {
    'DIRECTIONS':[
        'NORTH',
        'SOUTH',
        'EAST',
        'WEST',
        'NORTHWEST',
        'NORTHEAST',
        'SOUTHEAST',
        'SOUTHWEST',
        'UP',
        'DOWN',
        'IN',
        'OUT',
        'EXIT',
        'N',
        'S',
        'E',
        'W',
        'U',
        'D',
        'NW',
        'NE',
        'SE',
        'NW',
        ],
    'VERBS':[
        'QUIT',
        'GO',
        'L',
        'LOOK',
        'RUN',
        'WALK',
        'EAT',
        'KILL',
        ],
    'NOUNS':
     [
        'BEAR',
        'PRINCESS',
        ],
    'FILLER':[
        'THE',
        'OF',
        'A',
        'AN',],
    }
